apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/stefanprodan/podinfo/
  ref:
    branch: main  # 或者设置为你想要跟踪的分支
