apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nginx-kustomization
  namespace: default
spec:
  interval: 5m
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: nginx # 替换为你的 GitRepository 资源名称
  targetNamespace: default
  timeout: 2m
  validation: client
